[package]
name = "app"
version = "0.1.0"
authors = ["hzhou"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.6.2"
app_util = { path = "components/app_util" }

[workspace]
members = [
  "components/app_util",
]