
[sql1]
type = "query_list"
sql = "select id, name from student where grade = '${ABC}'"

[sql2]
type = "query_list"
sql = "select id, name from student where grade = '${ABC}' limit {{a}} offset {{b}}"

